os_local_image: "{{ lookup('env', 'OS_LOCAL_IMAGE') }}"
eib_source_image_name: "{{ os_local_image | basename }}"
eib_source_image_path: "{{ os_local_image | dirname }}"
eib_metal3_output_image_name: "{{ eib_source_image_name | splitext | join('.metal3') }}"
eib_mgmt_output_image_name: "{{ eib_source_image_name | splitext | join('.mgmt') }}"
working_dir: "{{ lookup('env', 'HOME') }}/metal3-demo-files"
eib_path: "{{ working_dir }}/eib"
eib_registration_code: "{{ lookup('env', 'EIB_REGISTRATION_CODE') }}"

# If eib_git_version is specified we build a local image
eib_container_image: "registry.opensuse.org/isv/suse/edge/edgeimagebuilder/containerfile/suse/edge-image-builder:1.0.1"
eib_git_version: ""

libvirt_network_dhcp: true

libvirt_images_dir: /var/lib/libvirt/images
image_cache_dir: "{{ libvirt_images_dir }}/image-cache"

cluster_rke2_version: "v1.28.8+rke2r1"

# Only used for the management-cluster image currently, to ensure we have
# enough space for RKE2 and other dependencies
eib_image_size: 5G
